module.exports = {
  // background: {
  //   backgroundImage: "linear-gradient(to top left, #00cc00 0%, #ccffcc 100%)",
  //   height: "300%",
  // },
  logo: {
    height: "8%",
    width: "8%",
  },
  navlink: {
    color: "black",
    fontSize: "large",
  },

  Name: {
    position: "absolute",
    top: "25%",
    left: "7%",
  },
  thirdpara: {
    position: "absolute",
    right: "10%",
  },
  // movingimg: {
  //   border: "solid black 2px",
  //   height: "50%",
  //   width: "60%",
  //   position: "absolute",
  //   top: "50%",
  //   left: "50%",
  //   transform: " translate(-50%,-50%)",
  //   backgroundImage: "url('NGO1\frontendsrclogo.png')",
  //   backgroundSize: "100% 100%",
  // },
  // Container1: {
  //   height: "40%",
  //   minHeight: "25%",
  //   maxWidth: "30%",
  //   color: "black",
  //   position: "absolute",
  //   top: "107%",
  //   left: "8%",
  //   borderRadius: "3%",
  // },
  Container2: {
    height: "40%",
    minHeight: "25%",
    maxWidth: "30%",
    color: "black",
    position: "absolute",
    top: "107%",
    left: "38%",
    borderRadius: "3%",
  },
  Container3: {
    height: "40%",
    minHeight: "25%",
    maxWidth: "30%",
    color: "black",
    position: "absolute",
    top: "107%",
    left: "68%",
    borderRadius: "3%",
  },
  Container4: {
    height: "40%",
    minHeight: "25%",
    maxWidth: "30%",
    color: "black",
    position: "absolute",
    top: "157%",
    left: "8%",
    borderRadius: "3%",
  },
  Container5: {
    height: "40%",
    minHeight: "25%",
    maxWidth: "30%",
    color: "black",
    position: "absolute",
    top: "157%",
    left: "38%",
    borderRadius: "3%",
  },
  Container6: {
    height: "40%",
    minHeight: "25%",
    maxWidth: "30%",
    color: "black",
    position: "absolute",
    top: "157%",
    left: "68%",
    borderRadius: "3%",
  },
  education: {
    height: "50%",
    width: "50%",
  },

  image: {
    position: "absolute",
    top: "130%",
    left: "67%",
  },
  image1: {
    position: "absolute",
    top: "180%",
    left: "67%",
  },
  image2: {
    position: "absolute",
    top: "230%",
    left: "67%",
  },
  image3: {
    position: "absolute",
    top: "280%",
    left: "67%",
  },
  image4: {
    position: "absolute",
    top: "330%",
    left: "67%",
  },
  image5: {
    position: "absolute",
    top: "380%",
    left: "67%",
  },
  donate: {
    position: "absolute",
    top: "210%",
    left: "35%",
  },
  donateIcon: {
    fontSize: "large",
  },
  img: {
    height: "100%",
    width: "50%",
    backgroundColor: "rgb(245, 190, 9)",
  },
  img2: {
    height: "50%",
    width: "50%",
    backgroundColor: "rgb(245, 190, 9)",
  },
  img3: {
    height: "80%",
    width: "50%",
    backgroundColor: "rgb(245, 190, 9)",
  },
  container: {
    border: "2px solid black",
    height: "5%",
    position: "absolute",
    top: "200%",
  },
  footer: {
    color: "black",
    backgroundColor: "rgb(245, 190, 9)",
  },
  quote: {
    fontSize: "large",
  },
  donateBox: {
    border: "solid black ",
    position: "absolute",
    top: "210%",
    height: "8%",
    minHeight: "64%",
    maxWidth: "100%",
    width: "100%",
    backgroundColor: "#000000",
  },
  gif: {
    left: "0%",
    height: "18%",
    width: "42%",
  },
  con: {
    maxwidth: "10%",
    // width: "30%",
    minHeight: "25%",
    border: "solid #f0f5f5",
    borderRadius: "2%",
  },
  adresscard: {
    backgroundColor: "#ffb3d9",
  },
  joinbox: {
    height: "25%",
    minHeight: "25%",
  },
  gpay: {
    height: "15%",
    width: "5%",
    position: "absolute",
    top: "7%",
  },
  paytm: {
    height: "15%",
    width: "5%",
    position: "absolute",
    top: "7%",
    right: "35%",
  },
  phonepe: {
    height: "35%",
    width: "22%",
    position: "absolute",
    // top: "1%",
    right: "35.5%",
  },
  sign: {
    position: "absolute",
    top: "10%",
    right: "2%",
  },
  qrcode: {
    height: "30%",
    width: "12.5%",
    position: "absolute",
    right: "6%",
    top: "45%",
  },
  bankdetails: {
    height: "65%",
    width: "20%",
    position: "absolute",
    top: "35%",
    right: "40%",
  },
  Container7: {
    // height: "40%",
    minHeight: "25%",
    maxWidth: "70%",
    width: "25%",
    color: "black",
    position: "absolute",
    top: "25%",
    right: "25%",
    borderRadius: "3%",
    backgroundColor: "black",
  },
  updates: {
    position: "absolute",
    top: "86%",
    color: "white",
  },
  arrow: {
    color: "pink",
    position: "absolute",
    top: "12%",
    right: "30%",
    // width: "10%",
  },
  facebook: {
    position: "absolute",
    // height: "10%",
    // weight: "10%",
    top: "85%",
    left: "32%",
  },
  instagram: {
    position: "absolute",

    top: "85%",
    left: "38%",
  },
  scanins: {
    color: "white",
    position: "absolute",
    top: "82%",
    right: "5%",
  },
};
